trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: BuildDev
    displayName: Build for DEV
    jobs:
      - job: BuildApp
        displayName: Build APP .net
        steps:
          - script: echo building dotnet app
            displayName: building dotnet app
          - script: echo running unit tests
            displayName: running unit tests
      - job: RestoreDependencies
        displayName: Restore dependencies
        dependsOn: BuildApp
        steps:
          - script: echo dotnet restore
            displayName: restoring project dependencies
  - stage: BuildStaging
    dependsOn: BuildDev
    condition: succeeded('BuildDev')
    displayName: Build for Staging
    jobs:
      - job: BuildApp
        displayName: Build APP .net
        steps:
          - script: echo building dotnet app
            displayName: building dotnet app
          - script: echo running unit tests
            displayName: running unit tests
  - stage: DeployProd
    dependsOn: 
      - BuildDev
      - BuildStaging
    condition: and(succeeded('BuildDev'), succeeded('BuildStaging'))
    displayName: Build for Prod
    jobs:
      - job: BuildApp
        displayName: Build APP .net
        steps:
          - script: echo building dotnet app
            displayName: building dotnet app
          - script: echo running unit tests
            displayName: running unit tests
